apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-bays
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/jvm-build-amuh-tenant/jvm-build-suite-application-yxdd/jvm-build-suite-component-bays@sha256:5341d0d5eab2c61a88a6a1c26d1d0d283a22a2305d420c4632cfa256c65feaca
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
